name: cdd-webapp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - flask=3.0.*
  - jinja2=3.1.*
  - werkzeug=3.0.*
  - weasyprint=60.*
  - reportlab=4.0.*
  - lxml=4.9.*
  - pillow=10.*
  - requests=2.31.*
  - beautifulsoup4=4.12.*
  - pip
  - pip:
    - flask-wtf==1.2.*
    - wtforms==3.1.*